### ISSUE TITLE
Cargo.toml links to relative path

### ISSUE THREAD

**Issue by dsgallups** [Zeenobit/moonshine_view#4]
```toml
[dependencies]
...
moonshine-core = { version = "0.3.*", path = "../core" }
```
:(

I think this might be fine? but the problem is examples cannot be run without pulling the core repo + renaming or making a sandbox and copying the code
